openapi: 3.2.0
info:
  description: This is a documentation for Eaas api-experiments
  version: 0.1.0
  title: Eaas api's Labeling Jobs API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: /
tags:
- name: labeling_jobs
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /labeling_jobs:
    post:
      tags:
      - labeling_jobs
      summary: New labeling jobs object
      description: Each labeling job represents dataset send to vendor to be annotated
      responses:
        '201':
          description: Created Successfully
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal Server Error
      security:
      - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - labeling_vendor_id
              - external_job_name
              - labeling_job_annotations_attributes
              properties:
                labeling_vendor_id:
                  type: integer
                  format: int
                  description: Vendor id
                  example: 1
                external_job_name:
                  description: job name
                  type: string
                  example: pupil size batch 1
                labeling_job_annotations_attributes:
                  description: Annotation attributes will be attached to labeling job
                  type: array
                  items:
                    type: string
                  example:
                  - emotions
        required: true
      operationId: postLabelingJobs
      x-operation-id-source: derived
  /labeling_jobs/{id}:
    delete:
      tags:
      - labeling_jobs
      summary: Delete labeling job object
      description: Delete labeling job object using labeling job id
      parameters:
      - name: id
        in: path
        description: Labeling job object id
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: Not content
        '404':
          description: Labeling job not found
      security:
      - basicAuth: []
      operationId: deleteLabelingJobsById
      x-operation-id-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
