openapi: 3.2.0
info:
  description: This is a documentation for Eaas api-experiments
  version: 0.1.0
  title: Eaas Entries API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: /
tags:
- name: Entries
paths:
  /entries:
    post:
      tags:
      - Entries
      summary: Add a new entry
      description: ''
      responses:
        '201':
          description: Success, entry created
        '422':
          description: Unprocessable Entity
      security:
      - basicAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                entry[media]:
                  type: string
                  description: entry media file
                  format: binary
                entry[storage_type]:
                  type: string
                  description: storage type(s3-efs-nas)
              required:
              - entry[media]
          application/json:
            schema:
              type: object
              properties:
                entry[media]:
                  type: string
                  description: entry media file
                  format: binary
                entry[storage_type]:
                  type: string
                  description: storage type(s3-efs-nas)
              required:
              - entry[media]
      operationId: postEntries
      x-operation-id-source: derived
  /entries/{entryID}:
    get:
      tags:
      - Entries
      summary: Get all entries
      description: ''
      responses:
        '200':
          description: Success
        '405':
          description: Invalid input
      parameters:
      - in: path
        name: entryID
        required: true
        schema:
          type: integer
          format: int64
      security:
      - basicAuth: []
      operationId: getEntriesByEntryID
      x-operation-id-source: derived
    put:
      tags:
      - Entries
      summary: Updates an entry
      description: ''
      parameters:
      - name: entryID
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Updated successfully
        '400':
          description: Bad request
        '404':
          description: Not found
        '422':
          description: Unprocessable Entity
      security:
      - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                entry:
                  type: object
                  properties:
                    data_split:
                      type: string
                      default: validation
      operationId: putEntriesByEntryID
      x-operation-id-source: derived
    delete:
      tags:
      - Entries
      summary: Delete entry by ID
      parameters:
      - in: path
        name: entryID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: Deleted successfully
        '400':
          description: Bad request
        '404':
          description: Not found
      security:
      - basicAuth: []
      operationId: deleteEntriesByEntryID
      x-operation-id-source: derived
  /entries/search_by_annotation:
    get:
      tags:
      - Entries
      summary: Get all entries by annotations
      responses:
        '200':
          description: Success
      parameters:
      - in: query
        name: key
        required: true
        schema:
          type: string
      - in: query
        name: value
        required: true
        schema:
          type: string
      - in: query
        name: source
        required: true
        schema:
          type: string
      security:
      - basicAuth: []
      operationId: getEntriesSearchByAnnotation
      x-operation-id-source: derived
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
